code --install-extension ms-vscode.azure-account
code --install-extension alefragnani.bookmarks
code --install-extension ms-vscode.cpptools
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension bibhasdn.django-html
code --install-extension PeterJausovec.vscode-docker
code --install-extension mikestead.dotenv
code --install-extension EditorConfig.editorconfig
code --install-extension dbaeumer.vscode-eslint
code --install-extension file-icons.file-icons
code --install-extension eamodio.gitlens
code --install-extension prisma.vscode-graphql
code --install-extension equinusocio.vsc-material-theme
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension christian-kohler.npm-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension ms-python.python
code --install-extension tomoki1207.selectline-statusbar
code --install-extension ms-vscode.sublime-keybindings
code --install-extension robertohuertasm.vscode-icons
