#!/bin/bash
code --install-extension teabyii.ayu
code --install-extension ms-vscode.azure-account
code --install-extension alefragnani.bookmarks
code --install-extension ms-vscode.cpptools
code --install-extension wmaurer.change-case
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension bibhasdn.django-html
code --install-extension ms-azuretools.vscode-docker
code --install-extension mikestead.dotenv
code --install-extension editorconfig.editorconfig
code --install-extension dbaeumer.vscode-eslint
code --install-extension file-icons.file-icons
code --install-extension eamodio.gitlens
code --install-extension ms-vscode.go
code --install-extension prisma.vscode-graphql
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension eriklynd.json-tools
code --install-extension equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension christian-kohler.npm-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension ms-python.python
code --install-extension tomoki1207.selectline-statusbar
code --install-extension foxundermoon.shell-format
code --install-extension ms-vscode.sublime-keybindings
code --install-extension mauve.terraform
code --install-extension octref.vetur
code --install-extension vscode-icons-team.vscode-icons
code --install-extension dotjoshjohnson.xml
